### PR TITLE
Card rshriv1

### PR DESCRIPTION
**Pull request by rsshrivastava7**
Final Pull Request

### CODE REVIEW

**Comment by keschae** [comment]
I have reviewed your code and have one request before it gets merged into the master branch and gets its grade. Could you modify your HTML component of your card so that it uses data binding (double curly braces) to dynamically create each one of those bits of data from your Student object? Currently it is hardcoded in the card.

**Comment by rsshrivastava7** [comment]
Made the required changes for the dynamic update for the card.

**Comment by rsshrivastava7** [comment]
Hello Professor,

I have made the required changes as suggested.


Thanks,
Rishi Shrivastava

**Comment by keschae** [comment]
Thank you for the changes. I will merge the branch and finish grading.

**Pull request merged**
